FullRepositoryId        = "ProjetoGeradorMassaDadosAws/Infra-SqsGeracaoArquivoDLQ"
BranchName              = "main"
AWS_ACCESS_KEY_ID       = "Sua chave aqui"
AWS_SECRET_ACCESS_KEY   = "Seu segredo aqui"
PipelineName            = "pipeline_sqs_geracao_arquivo_DLQ"
CodebuildName           = "codebuild_sqs_geracao_arquivo_DLQ"
BucketName              = "pipeline-sqs-geracao-arquivo-bucket-dlq"