FullRepositoryId        = "ProjetoGeradorMassaDadosAws/Infra-SqsGeracaoArquivo"
BranchName              = "main"
AWS_ACCESS_KEY_ID       = "Sua chave aqui"
AWS_SECRET_ACCESS_KEY   = "Seu segredo aqui"
PipelineName            = "pipeline_sqs_geracao_arquivo"
CodebuildName           = "codebuild_sqs_geracao_arquivo"
BucketName              = "pipeline-sqs-geracao-arquivo-bucket"